# Generated by Django 5.0.14 on 2026-07-01 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(default='Web', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GroundTruth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField()),
                ('expected_category', models.CharField(max_length=100)),
                ('expected_priority', models.CharField(choices=[('P0', 'P0 (Critical)'), ('P1', 'P1 (High)'), ('P2', 'P2 (Medium)'), ('P3', 'P3 (Low)')], max_length=2)),
                ('expected_needs_human', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('associated_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='triage_app.customermessage')),
            ],
        ),
        migrations.CreateModel(
            name='TriageResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('priority', models.CharField(choices=[('P0', 'P0 (Critical)'), ('P1', 'P1 (High)'), ('P2', 'P2 (Medium)'), ('P3', 'P3 (Low)')], max_length=2)),
                ('summary', models.TextField()),
                ('suggested_action', models.TextField()),
                ('needs_human', models.BooleanField(default=False)),
                ('confidence', models.FloatField()),
                ('tool_calls_log', models.TextField(blank=True, help_text='JSON representation of tool calls and results', null=True)),
                ('raw_json_response', models.TextField(blank=True, null=True)),
                ('latency', models.FloatField(default=0.0, help_text='Latency in seconds')),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('cost', models.FloatField(default=0.0)),
                ('is_overridden', models.BooleanField(default=False)),
                ('overridden_category', models.CharField(blank=True, max_length=100, null=True)),
                ('overridden_priority', models.CharField(blank=True, choices=[('P0', 'P0 (Critical)'), ('P1', 'P1 (High)'), ('P2', 'P2 (Medium)'), ('P3', 'P3 (Low)')], max_length=2, null=True)),
                ('overridden_needs_human', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='triage', to='triage_app.customermessage')),
            ],
        ),
    ]
