# Generated by Django 5.0.14 on 2026-07-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='triageresult',
            name='overridden_suggested_action',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='triageresult',
            name='overridden_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
