# Generated by Django 5.0.14 on 2026-07-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage_app', '0002_triageresult_overridden_suggested_action_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KBArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Search match keyword (e.g. pending payment)', max_length=100, unique=True)),
                ('content', models.TextField(help_text='Article contents and guidelines')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
