# Generated by Django 5.0.14 on 2026-07-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage_app', '0003_kbarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='triageresult',
            name='auto_reply_draft',
            field=models.TextField(blank=True, null=True),
        ),
    ]
